#!/usr/bin/env bash
# Script to displays list of currently running processes
# Its Must show all processes, for all thes users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierarchy

ps -a -x -u -f
