#!/usr/bin/env bash
# Script to extends previous exercise command and displays line containing the bash word, this allowing you to easily get the PID of your Bash process
# Not to use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
