#!/usr/bin/env bash
# To kills the infinity and beyond  program using sigkill signal

# To Get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# To Terminate the infinate process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
