#!/usr/bin/env bash
# Its is a script to displays
# A nfinity and beyond indefinitely
# With the sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
