#!/usr/bin/env bash
# To This script creates the file /var/run/holbertonscript.pid containing its PID
# To Displays To infinity and beyond indefinitely
# To Displays I hate the kill command when receiving a SIGTERM signal
# To Displays Y U no love me?! when receiving a SIGINT signal
# To Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal

function love() {
    rm /var/run/holbertonscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/holbertonscript.pid
while [ true ]; do
    echo To infinity and beyond;
done
