#!/usr/bin/env bash
# To Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

for numba in {1..100}
do
	if (( numba % 3 == 0 && numba % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( numba % 3 == 0 ))
	then
		echo "Fizz"
	elif (( numba % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$numba"
	fi
done
