#!/usr/bin/env bash
# To Displays a contents of the file `/etc/passwd`.
# Only displays a username, user id, and user home directory path.

while IFS= read -r passwd;
do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
