#!/usr/bin/env bash
# To Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".

begin=0

while [ $begin -lt 10 ]
do
	if [ $begin -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( begin++ ))
done
