#!/usr/bin/env bash
# To Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hrs=0

while [ $hrs -le 12 ]
do
	echo "Hour: $hrs"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hrs++ ))
done
